
services:
  migration:
    build:
      context: .
      dockerfile: ./containers/migrator/Dockerfile
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sam-network
    restart: "no"  # Don't restart the migrator after it completes

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - sam-network
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    user: postgres
    container_name: postgres
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 30s
      retries: 5
    environment:
      # POSTGRES_USER: yehtetaung
      POSTGRES_PASSWORD: password
      POSTGRES_DB: newdb
    ports:
      - "5432:5432" # Expose PostgreSQL on the default port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persist data
    networks:
      - sam-network

  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
    ports:
      - "9000:9000"  # Expose MinIO API (Object Storage) on port 4200
      - "4300:4300"  # Expose MinIO Console (Web UI) on port 4300
    volumes:
      - minio_data:/data
    networks:
      - sam-network
    command: server /data --console-address ":4300"
    restart: always

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:  # Persist data for MinIO

networks:
  sam-network:
    driver: bridge
